---
- name: "Copy Google Download Script"
  copy:
    src: gdown.pl
    dest: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: "Download GROMACS container"
  command: /home/ubuntu/gdown.pl https://drive.google.com/file/d/1SXcJ3RlUzrwB2Wq4Umo-XSrBjewgCdKn/view gromacs
  args:
    chdir: /home/ubuntu/

- name: "Download Benchmarks"
  get_url:
    url: "{{ item }}"
    dest: /home/ubuntu/
  with_items:
  - https://www.mpibpc.mpg.de/15101317/benchMEM.zip
  - https://www.mpibpc.mpg.de/15101328/benchRIB.zip
  become: yes
  become_user: ubuntu
  become_method: sudo

- name: "Extract Benchmarks"
  unarchive:
    src: "/home/ubuntu/{{ item }}"
    dest: /home/ubuntu/
  with_items:
  - benchMEM.zip
  - benchRIB.zip
