---
#- name: "Create Singularity Image File"
#  copy:
#    src: singularity/opm.sspec
#    dest: /home/ubuntu/singularity/
#
#- name: "Run Singularity Build"
#  command: /usr/local/bin/singularity build opm /home/ubuntu/singularity/opm.sspec
- name: "Install OPM from repository"
  apt_repository:
    repo: ppa:opm/ppa

- name: "Install MPI and OPM"
  apt:
    pkg:
    - mpi-default-bin
    - libopm-simulators-bin
    update_cache: yes

- name: "Download benchmarks"
  git:
    repo: https://github.com/OPM/opm-data.git
    dest: /home/ubuntu/opm/
