---
- name: "Create Singularity Image File"
  copy:
    src: singularity/opm.sspec
    dest: /home/ubuntu/singularity/

- name: "Run Singularity Build"
  command: /usr/local/bin/singularity build opm /home/ubuntu/singularity/opm.sspec

- name: "Download benchmarks"
  git:
    repo: https://github.com/OPM/opm-data.git
    dest: /home/ubuntu/opm-data/
  become: yes
  become_user: ubuntu
  become_method: sudo
