---
- hosts: "localhost"
  connection: "localhost"
  gather_facts: no
  tasks:
  - name: "Build list of instance IDs by instance name"
    ec2_instance_facts:
      region: "us-east-1"
      filters:
        "tag:tool": ansible
        instance-state-name: running
    register: ec2

  - name: "Terminate instances that were previously launched"
    ec2:
      ec2_region: "us-east-1"
      state: 'absent'
      instance_ids: '{{ item.instance_id }}'
    with_items: "{{ ec2.instances }}"



