---
- hosts: "localhost"
  connection: "localhost"
  vars:
    ec2_region: "us-east-1"
    ec2_new_type: "c5.large"
  tasks:
  - name: "Build list of instance IDs by instance name"
    ec2_instance_facts:
      region: "{{ ec2_region }}"
      filters:
        "tag:tool": ansible
        instance-state-name: 'running'
    register: ec2

  - name: "Stop instances that were previously launched"
    ec2:
      ec2_region: "{{ ec2_region }}"
      state: 'stopped'
      instance_ids: "{{ item.instance_id }}"
      wait: True
    when: 
    with_items: "{{ ec2.instances }}"

  - name: "Resize all instances"
    command: "aws ec2 modify-instance-attribute --region {{ ec2_region }} --instance-id {{ item.instance_id }} --instance-type '{\"Value\": \"{{ ec2_new_type }}\"}'"
    with_items: "{{ ec2.instances }}"
