---
- hosts: "localhost"
  connection: "localhost"
  vars:
    ec2_region: "us-east-1"
  tasks:
  - name: "Build list of instance IDs by instance name"
    ec2_instance_facts:
      region: "{{ ec2_region }}"
      filters:
        "tag:tool": ansible
        instance-state-name: 'stopped'
    register: ec2

  - name: "Stop instances that were previously launched"
    ec2:
      ec2_region: "{{ ec2_region }}"
      state: 'running'
      instance_ids: "{{ item.instance_id }}"
      wait: True
    when: 
    with_items: "{{ ec2.instances }}"
