---
- hosts: "{{ groups.all | random }}"
  remote_user: ubuntu
  gather_facts: false
  vars:
    ec2_type: "t2.micro"
    n_processes: "1"
    test_case_path: "/home/ubuntu/benchRIB.tpr"
    output_dir: "/tmp/"
    test_target: "opm"
  tasks:
    - name: "Generate test cases"
      include: "tasks/{{ test_target }}/test.yml"

