---
- hosts: "{{ groups.all | random }}"
  remote_user: ubuntu
  gather_facts: false
  vars:
    ec2_type: "t2.micro"
    n_processes: "1"
    test_case_path: "/home/ubuntu/opm/spe1/SPE1CASE1.DATA"
    output_dir: "/tmp/"
  tasks:
    - name: "Run test cases of {{ ec2_type }} using {{ n_processes }}"
      shell: |
        whoami
        if [ ! -f hostfile ]; then
          echo "{{ item }}" >> hostfile
          flow "{{ test_case_path }}"
        else
          echo "{{ item }}" >> hostfile
          mpirun --hostfile hostfile flow "{{ test_case_path }}"
        fi
        exit 0
      with_items: "{{ hostvars[inventory_hostname]['private_hosts'] }}"
      register: testcase
      sudo: yes
      sudo_user: ubuntu

    - name: "Clean up Hostfile"
      file:
        path: /home/ubuntu/hostfile
        state: absent

    - name: "Create a file if it does not exists"
      file:
        path: "{{ output_dir }}/test_{{ ec2_type }}_{{ std_idx}}.out"
        state: touch
      with_items: "{{ testcase.results }}"
      loop_control:
        index_var: std_idx
      delegate_to: localhost

    - name: "Write Results"
      lineinfile:
        line: "{{ item.stdout }}"
        dest: "{{ output_dir }}/test_{{ ec2_type }}_{{ std_idx}}.out"
        insertafter: EOF
      with_items: "{{ testcase.results }}"
      loop_control:
        index_var: std_idx
      delegate_to: localhost

#    - name: "Save results"
#        debug: msg="{{ item.stdout }}"
#      with_items: "{{ testcase.results }}"
#      delegate_to: localhost


